CREATE TABLE CLTGROUP(
    ID INT(15) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30),
    DESCRIPTION VARCHAR(100)
);
CREATE TABLE CLUSTER
(
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   GROUP_ID INT(15) NOT NULL,
   NAME VARCHAR(20) NOT NULL,
   CREATE_DATE DATE,
   PASSWORD_HASH VARCHAR(128) NOT NULL,
   FOREIGN KEY (GROUP_ID)
    REFERENCES CLTGROUP(ID)
);
 
 CREATE TABLE CLTMODULE(
    ID INT(15) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100)
);
 
CREATE TABLE CLTACCESS(
    MODULE_ID INT(15) NOT NULL,
    GROUP_ID INT(15) NOT NULL,
	PERMISSION INT(1), NOT NULL,
    FOREIGN KEY (MODULE_ID)
        REFERENCES CLTMODULE(ID),
    FOREIGN KEY (GROUP_ID)
        REFERENCES CLTGROUP(ID)
);