CREATE TABLE RELOADSESSION(
	SESSION_ID VARCHAR(40) UNIQUE,
    REQUEST_ID VARCHAR(130),
    TRX_TYPE INT(1),
    MSISDN VARCHAR(20),
    ACCOUNT VARCHAR(100),
    AMOUNT FLOAT(14,2),
    TRX_STATE INT(1),
    EXPIRY DATE,
    TARGET INT(2),
    TRANS_ID INT(12),
    TRS_ID INT(12),
    DST_ID INT(12),
    ORIGINATOR VARCHAR(25),
    PRIMARY KEY (REQUEST_ID, TRX_TYPE)
);
