INSERT INTO RELOAD_CHANNEL(ID, NAME, SUB_CHANNEL, DESCRIPTION, CHANNEL_TYPE, MAX_AMOUNT, MIN_AMOUNT, RESERVATION_TIME)
VALUES(1,"SC_SHOPS","TELLER","Swisscom Shop Online Reloads (Webcash)",9,300,-10,3600);

INSERT INTO CHANNNEL_CASH_TYPE(RELOAD_CHANNEL_ID, CASH_TYPE, CASH_NAME)
VALUES(1,55,"Partner");