ALTER TABLE RELOADSESSION
ADD CHANNEL_TYPE varchar(20),
ADD CASH_TYPE varchar(20);

CREATE TABLE RELOAD_CHANNEL(
	ID int(5) PRIMARY KEY,
    NAME varchar(16),
    SUB_CHANNEL varchar(50),
    DESCRIPTION varchar(100),
    CHANNEL_TYPE varchar(20),
    MAX_AMOUNT float(5,2),
    MIN_AMOUNT float(5,2),
    RESERVATION_TIME int(10),
	CONSTRAINT RC UNIQUE (ID,NAME),
	FOREIGN KEY (NAME) REFERENCES CLUSTER(NAME)
);

CREATE TABLE CHANNEL_CASH_TYPE(
	RELOAD_CHANNEL_ID INT(5),
    CASH_TYPE varchar(20),
    CASH_NAME varchar(20),
    primary key(RELOAD_CHANNEL_ID, CASH_TYPE)
	foreign key (RELOAD_CHANNEL_ID) REFERENCES RELOAD_CHANNEL(ID)
);